import os
import random
import datetime
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from db_setup import DistrictSummary, CommunityData

from dotenv import load_dotenv
load_dotenv()

DATABASE_URL = os.getenv('DATABASE_URL')
if not DATABASE_URL:
    raise ValueError("DATABASE_URL must be set in .env")

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def seed_all_india():
    db = SessionLocal()
    try:
        # 1. Read all district names from the file generated by jq
        with open('all_districts.txt', 'r') as f:
            # Strip quotes and newlines, ignore empties and nulls
            districts = [line.strip().strip('"') for line in f if line.strip() and line.strip() != '"null"']
        
        total_districts = len(districts)
        print(f"Loaded {total_districts} districts. Beginning seeding...")
        
        # 2. Clear existing demo data
        db.query(CommunityData).delete()
        db.query(DistrictSummary).delete()
        db.commit()

        # 3. Insert fake data for each district
        for i, dist_name in enumerate(districts):
            if i % 50 == 0:
                print(f"Seeding district {i+1}/{total_districts}...")

            # Generate random realistic coverage stats
            # Skew higher for general realism, but leave a few outliers
            base_coverage = random.choice([
                random.randint(60, 75),  # 20% chance of being moderate-low
                random.randint(75, 95),  # 60% chance of normal
                random.randint(75, 95),
                random.randint(75, 95),
                random.randint(90, 99)   # 20% chance of great
            ])
            
            summary = DistrictSummary(
                district_name=dist_name,
                mmr_coverage=min(100, base_coverage + random.randint(-5, 5)),
                dpt_coverage=min(100, base_coverage + random.randint(-4, 6)),
                polio_coverage=min(100, base_coverage + random.randint(0, 8)),
                record_count=random.randint(20, 250), # Random number of logs submitted
                last_updated=datetime.datetime.utcnow()
            )
            db.add(summary)
            
            # Add 2 individual records as "latest activity" just to populate CommunityData
            for _ in range(2):
                record = CommunityData(
                    district_name=dist_name,
                    vaccine_type=random.choice(["MMR", "DPT", "Polio", "BCG"]),
                    coverage_pct=base_coverage + random.randint(-15, 10),
                    last_updated=datetime.datetime.utcnow()
                )
                db.add(record)
                
        db.commit()
        print(f"✅ Successfully seeded {total_districts} districts across India!")

    except Exception as e:
        db.rollback()
        print(f"Error seeding data: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    seed_all_india()
